# Generated by Django 2.2.6 on 2019-10-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('runtime', models.TimeField(max_length=20)),
                ('rating', models.FloatField(max_length=10)),
                ('genre', models.CharField(max_length=100)),
                ('release_date', models.DateField(max_length=10)),
            ],
        ),
    ]
