# Generated by Django 2.2.6 on 2019-10-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(max_length=2),
        ),
    ]
